const images = {
  a: require("./img/a.png"),
  i: require("./img/i.png"),
  u: require("./img/u.png"),
  e: require("./img/e.png"),
  o: require("./img/o.png"),
  ka: require("./img/ka.png"),
  ki: require("./img/ki.png"),
  ku: require("./img/ku.png"),
  ke: require("./img/ke.png"),
  ko: require("./img/ko.png"),
  sa: require("./img/sa.png"),
  shi: require("./img/shi.png"),
  su: require("./img/su.png"),
  se: require("./img/se.png"),
  so: require("./img/so.png"),
  ta: require("./img/ta.png"),
  chi: require("./img/chi.png"),
  tsu: require("./img/tsu.png"),
  te: require("./img/te.png"),
  to: require("./img/to.png"),
  na: require("./img/na.png"),
  ni: require("./img/ni.png"),
  nu: require("./img/nu.png"),
  ne: require("./img/ne.png"),
  no: require("./img/no.png"),
  ha: require("./img/ha.png"),
  hi: require("./img/hi.png"),
  fu: require("./img/fu.png"),
  he: require("./img/he.png"),
  ho: require("./img/ho.png")
};

export default images;
